### ISSUE TITLE
wifi.cfg does not comply with polycomConfig.xsd

### ISSUE THREAD

**Issue by shivtorov** [greiginsydney/000000000000.cfg#2]
The element 'polycomConfig' has invalid child element 'wifi':
https://github.com/greiginsydney/000000000000.cfg/blob/0348b4b3b99b04261cc58c8c97194786a50f09f9/wifi.cfg#L8

**Comment by shivtorov** [comment]
The elements 'device.wifi.radio' and 'device.wifi.psk' must be children of 'device.wifi' element

**Comment by shivtorov** [comment]
Pull request **#3** will fix the issue 
(testing links to pull requests)

**Comment by greiginsydney** [comment]
Thanks Mike.
